/**
 * Interview session lifecycle management.
 *
 * Manages: session creation, state transitions, message recording, and history retrieval.
 *
 * Session state machine:
 *   CREATED → ACTIVE → COMPLETED | ABANDONED
 *
 * Message roles:
 *   INTERVIEWER — questions generated by InterviewAgent
 *   CANDIDATE   — answers submitted by the user
 *
 * Session input surface:
 *   resume text, job description, company (optional), experience level,
 *   interview type (HR / TECHNICAL / SYSTEM_DESIGN / BEHAVIOURAL), topic focus (optional)
 *
 * Tables: sessions, messages
 *
 * SessionHistoryTool in the agent package reads from this package's repository.
 * EventPublisher fires session.completed on session end.
 */
package com.interviewlab.session;
